site_name: Archetype ECS lib Documentation
site_author: PirateJL
copyright: Copyright &copy; 2026 PirateJL
theme:
  name: material
  language: en
  #logo: assets/logo.svg
  # favicon: assets/favicon.png
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
    # - content.action.edit
    - content.action.view
    - navigation.tracking
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github
    # edit: material/pencil
    view: material/eye
    annotation: material/help-circle-outline
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

#exclude_docs: |
#  documentation-interne

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
      line_anchors: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - attr_list
  - toc:
      permalink: true
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

site_dir: "public"

repo_name: Github
repo_url: https://github.com/PirateJL/archetype-ecs-lib
edit_uri: !ENV [EDIT_URI, "blob/gh-pages/"]

extra:
  version:
    provider: mike
    alias: true
  social:
    - icon: fontawesome/solid/file-pdf
      link: !ENV [PDF_LINK, '/assets/document.pdf']
      name: Version PDF
    - icon: fontawesome/brands/github
      link: https://github.com/
      name: Github
    - icon: fontawesome/brands/npm
      link: https://www.npmjs.com/package/archetype-ecs-lib
      name: NPM Package

plugins:
  with-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT
      output_path: assets/document.pdf
      cover_subtitle: "La gestion de contenu intégrée"
      cover_logo: assets/logo_couleur.png
  search:
    enabled: true
    lang: en
  git-revision-date-localized:
    enable_creation_date: true
    enabled: true

extra_javascript:
  - javascript/extra.js
