# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
    branches: [master]
    paths-ignore:
      - coverage.svg
  pull_request:
    paths-ignore:
      - coverage.svg

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['22.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm run reload-packages

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test
      
      - name: Generate Coverage Badge (SVG)
        uses: jaywcjlove/coverage-badges-cli@v2.2.0
        with:
          source: coverage/coverage-summary.json
          output: coverage.svg
          style: flat
          jsonPath: total.lines.pct

      - name: Upload Coverage Badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: coverage.svg
  
  update-coverage:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions:
      contents: write
    
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: gh-pages

      - name: Download coverage badge artifact into workspace
        uses: actions/download-artifact@v4
        with:
          name: coverage-badge
          path: .

      - name: Commit and Push coverage.svg to gh-pages
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          if [ ! -f "coverage.svg" ]; then
            echo "coverage.svg not found, skipping."
            exit 0
          fi

          git add -f coverage.svg

          # Stop if no change
          git diff --staged --quiet && { echo "No changes"; exit 0; }

          git commit -m "Update coverage badge [skip ci]"
          git push origin gh-pages
